matrix:
  include:
    - language: node_js
      node_js: 12
      install:
        - npm install
      script:
        - npm run lint
        - npm run build
    - language: go
      os: linux
      dist: bionic
      go: 1.14.x
      node_js: 12
      before_install:
        - sudo apt update
        - sudo apt-get -y install gcc libgtk-3-dev libappindicator3-dev webkit2gtk-4.0
      install:
        - npm install
        - go get -u github.com/gobuffalo/packr/packr
      script:
        - npm run lint
        - npm run build
        - cd photonai-explorer-serv/
        - cp -r ../dist/ ./dist/
        - $GOPATH/bin/packr
        - go build -o photon_explorer .
    - language: go
      os: osx
      go: 1.14.x
      node_js: 12
      install:
        - npm install
        - go get -u github.com/gobuffalo/packr/packr
      script:
        - npm run lint
        - npm run build
        - cd photonai-explorer-serv/
        - cp -r ../dist/ ./dist/
        - $GOPATH/bin/packr
        - go build -o photon_explorer_mac .
