language: node_js
os: linux
dist: bionic
jobs:
  include:
    - language: node_js
      os: linux
      dist: bionic
      node_js: 12
      install:
        - npm install
      script:
        - npm run lint
        - npm run build
    - language: go
      os: linux
      dist: bionic
      go: 1.14.x
      node_js: 12
      before_install:
        - eval "$(ssh-agent -s)"
        - echo $SSHKEY | base64 -d > /tmp/sshkey
        - chmod 600 /tmp/sshkey
        - ssh-add /tmp/sshkey
        - sudo apt update
        - sudo apt-get -y install gcc libgtk-3-dev libappindicator3-dev webkit2gtk-4.0
      install:
        - npm install
        - go get -u github.com/gobuffalo/packr/packr
        - go get -u github.com/akavel/rsrc
      script:
        - npm run lint
        - npm run build
        - cd photonai-explorer-serv/
        - rm -r ./dist/
        - cp -r ../dist/ ./dist/
        - $GOPATH/bin/packr
        - go build -o photonai_explorer .
        - rsrc -manifest photonai_explorer.manifest
        - env GOOS=windows GOARCH=amd64 go build -ldflags="-H windowsgui" -o photonai_explorer.exe .
      deploy:
        provider: script
        skip_cleanup: true
        script: "rsync -av -e 'ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR' $TRAVIS_BUILD_DIR/photonai-explorer-serv/{photonai_explorer,photonai_explorer.exe} $SSHUSER@$SSHSERVER:/"
        on:
          branch: feature/add_deployment
    - language: go
      os: osx
      go: 1.14.x
      node_js: 12
      addons:
        homebrew:
          packages:
            - graphicsmagick
            - imagemagick
          update: true
      before_install:
        - eval "$(ssh-agent -s)"
        - echo $SSHKEY | base64 -d > /tmp/sshkey
        - chmod 600 /tmp/sshkey
        - ssh-add /tmp/sshkey
        - npm install --global create-dmg
      install:
        - npm install
        - go get -u github.com/gobuffalo/packr/packr
      script:
        - npm run lint
        - npm run build
        - cd photonai-explorer-serv/
        - rm -r ./dist/
        - cp -r ../dist/ ./dist/
        - $GOPATH/bin/packr
        - go build -o ./.build-mac/PHOTONAI\ Explorer.app/Contents/MacOS/photonai_explorer_mac .
        - cd ./.build-mac/
        - create-dmg PHOTONAI\ Explorer.app || a=$?; if [ $a -eq 2 ]; then return 0; else return $a; fi # ignore error code 2
      deploy:
        provider: script
        skip_cleanup: true
        script: "rsync -av -e 'ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR' $TRAVIS_BUILD_DIR/photonai-explorer-serv/.build-mac/ $SSHUSER@$SSHSERVER:/"
        on:
          branch: feature/add_deployment
