name: Nodejs publish online @ explorer.photon-ai.com

# on:
#   release:
#     types: [published]
on:
  push:
    branches: [ github-actions ]

jobs:
  build_and_publish:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH Key
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSHKEY }}"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Upload dist folder
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: rsync -av --delete -e 'ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR' ./dist/ "${{ secrets.SSHUSER }}"@"${{ secrets.SSHSERVER }}":/
